services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $encryptedConnections: '%aeliot.doctrine_encrypted_field.encrypted_connections%'

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags: [doctrine.event_subscriber]

    Aeliot\Bundle\DoctrineEncryptedField\:
        resource: '../../*'
        exclude: '../../{Doctrine,Enum,Exception,Resources}'


    Aeliot\Bundle\DoctrineEncryptedField\EventListener\LoadClassMetadataListener:
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
