name: Automated Testing

on:
  push:

permissions:
  contents: read

jobs:
  composer:
    name: Validate composer files
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - lock-version: '5.4'
          - lock-version: '6.0'
          - lock-version: '6.4'
          - lock-version: '7.0'
          - lock-version: '7.1'
          - lock-version: '7.2'

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-php

      - name: Set versions
        run: cp 'composer.${{ matrix.lock-version }}.lock' composer.lock

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

  composer-require-checker:
    name: Check composer requirements
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-php

      - name: Set versions
        run: cp composer.7.2.lock composer.lock

      - uses: ./.github/actions/setup-composer
      - uses: ./.github/actions/setup-phive

      - name: Check composer requirements
        run: composer require-check

  composer-unused:
    name: Check unused composer requirements
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-php

      - name: Set versions
        run: cp composer.7.2.lock composer.lock

      - uses: ./.github/actions/setup-composer
      - uses: ./.github/actions/setup-phive

      - name: Check unused composer requirements
        run: composer unused

  cs-fixer:
    name: Check code style with CS Fixer
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-php

      - name: Set versions
        run: cp composer.6.4.lock composer.lock

      - uses: ./.github/actions/setup-composer
      - uses: ./.github/actions/setup-phive

      - name: Check code style
        run: composer cs-fixer-check -- --show-progress=none

  phpstan:
    name: Static analyze with PHPStan
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-php

      - name: Set versions
        run: cp composer.6.4.lock composer.lock

      - uses: ./.github/actions/setup-composer

      - name: Static analyze with PHPStan
        run: |
          composer run phpstan-clear && \
          composer run phpstan-analyse -- --no-progress

  test-unit:
    name: 'Tests: Unit'
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - lock-version: '5.4'
          - lock-version: '6.0'
          - lock-version: '6.4'
          - lock-version: '7.0'
          - lock-version: '7.1'
          - lock-version: '7.2'

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-php

      - name: Set versions
        run: cp 'composer.${{ matrix.lock-version }}.lock' composer.lock

      - uses: ./.github/actions/setup-composer

      - name: 'Run testsuite: Unit'
        run: composer run test-unit

  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Yamllint Action
        uses: bewuethr/yamllint-action@v1.3.0
        with:
          config-file: scripts/yamllint.yaml
